var metahill=metahill||{};metahill.base={};metahill.base.support={};
$(function(){var a=navigator.userAgent.toLowerCase();metahill.base.support.isChrome=-1<a.indexOf("chrome");metahill.base.support.isOpera=-1<a.indexOf("opera");metahill.base.support.isFirefox=-1<a.indexOf("firefox");metahill.base.support.isInternetExplorer=-1<navigator.appName.indexOf("Microsoft")||-1<a.indexOf("msie");metahill.base.support.isMac=-1<navigator.platform.toLowerCase().indexOf("mac");metahill.base.support.isWindows=-1<navigator.appVersion.indexOf("Win");metahill.base.support.isInternetExplorer&&
-1===window.location.toString().indexOf("get-a-modern-browser")&&(window.location="http://www.metahill.com/get-a-modern-browser.php")});String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};String.prototype.ltrim=function(){return this.replace(/^\s+/,"")};String.prototype.rtrim=function(){return this.replace(/\s+$/,"")};Array.prototype.remove=function(a,d){var b=this.slice((d||a)+1||this.length);this.length=0>a?this.length+a:a;return this.push.apply(this,b)};metahill=metahill||{};metahill.helper={};
metahill.helper.submitHttpRequest=function(a,d,b){var c=new XMLHttpRequest;c.open("POST","php/"+a);c.onload=function(){if(200===c.status)console.log("http request: ok. "+c.responseText),void 0!==b&&b(c.getResponseHeader("Content-Description"));else{var a=c.getResponseHeader("Content-Description");console.log("http request: something went terribly wrong("+a+"), "+c.status+":"+c.statusText)}};a=new FormData;for(var e in d)a.append(e,d[e]);c.send(a)};
metahill.helper.toHHMMSS=function(a){return(new Date(a)).toTimeString().replace(/.*(\d{2}:\d{2}:\d{2}).*/,"$1")};metahill.helper.getSimpleText=function(a){return a.clone().children().remove().end().text().trim()};metahill.helper.openUrlInNewTab=function(a){window.open(a,"_blank").focus()};metahill.helper.getGetParameters=function(){for(var a=window.location.search.substr(1).split("&"),d={},b=0;b<a.length;b++){var c=a[b].split("=");d[c[0]]=c[1]}return d};metahill.helper.htmlEncode=function(a){return $(document.createElement("div")).text(a).html()};
metahill.helper.htmlDecode=function(a){return $(document.createElement("div")).html(a).text()};metahill.sound={};metahill.sound.playUserAddressed=function(){var a=new Audio("sound/user-addressed.wav");return function(){metahill.modals.preferences.enable_notification_sounds&&a.play()}}();metahill=metahill||{};metahill.formatMessages={};
metahill.formatMessages.replaceTextSmilies=function(){function a(a){return a.replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1")}var d={":)":"smile.png",":-)":"smile.png","=)":"smile.png",":D":"biggrin.png",":-D":"biggrin.png","=D":"biggrin.png",";)":"wink.png",";D":"wink.png",";-)":"wink.png",";-D":"wink.png",":?":"confused.png",":-?":"confused.png",":(":"sad.png",":-(":"sad.png",":'(":"crying.png",">.<":"pinch.png",">_<":"pinch.png","=8-)":"cool.png",":S":"unsure.png",":s":"unsure.png","^^":"squint.png","<3":"love.png"},
b={":angry":"angry.png",":biggrin":"biggrin.png",":blink":"blink.png",":confused":"confused.png",":cool":"cool.png",":crying":"crying.png",":cursing":"cursing.png",":evil":"evil.png",":huh":"huh.png",":love":"love.png",":mellow":"mellow.png",":pinch":"pinch.png",":rolleyes":"rolleyes.png",":sad":"sad.png",":sleeping":"sleeping.png",":smile":"smile.png",":squint":"squint.png",":thumbdown":"thumbdown.png",":thumbsup":"thumbsup.png",":thumbup":"thumbup.png",":tongue":"tongue.png",":unsure":"unsure.png",
":w00t":"w00t.png",":wacko":"wacko.png",":whistling":"whistling.png",":wink":"wink.png"};return function(c){if(!metahill.modals.preferences.enable_smilies)return c;Object.keys(b).forEach(function(d){var g='<img src="img/smilies/'+b[d]+'"></img>';-1!==c.indexOf(d)&&(d=RegExp("("+a(d)+")(?=(?:(?:[^`]*`){2})*[^`]*$)","g"),c=c.replace(d,g))});Object.keys(d).forEach(function(b){var g='<img src="img/smilies/'+d[b]+'"></img>';-1!==c.indexOf(b)&&(b=RegExp("("+a(b)+")(?=(?:(?:[^`]*`){2})*[^`]*$)","g"),c=c.replace(b,
g))});return c}}();metahill.formatMessages.boldItalicsCode=function(a){if(!metahill.modals.preferences.enable_formatting)return a;a=a.replace(/(\*[^`]+\*|`[^`]+`)/g,function(a,b){return"*"===b[0]?b.replace(/^\*(.*)\*$/,"<strong>$1</strong>"):b});a=a.replace(/(_[^`]+_|`[^`]+`)/g,function(a,b){return"_"===b[0]?b.replace(/^_(.*)_$/,"<em>$1</em>"):b});return a=a.replace(/`(.+?)`/g,"<code>$1</code>")};
metahill.formatMessages.styleMessage=function(a,d){a=metahill.formatMessages.makeLinksClickable(a);a=metahill.formatMessages.replaceTextSmilies(a);return a=metahill.formatMessages.boldItalicsCode(a)};
metahill.formatMessages.makeLinksClickable=function(a){function d(a){a=a.replace(/_/g,"%5f");return 0===a.indexOf("http")?'<a target="_blank" href="'+a+'">'+a+"</a>":'<a target="_blank" href="http://'+a+'">'+a+"</a>"}var b=/((http:\/\/|www)[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/gi;return function(a){return null===a||void 0===a?"":a.replace(b,d)}}();$(function(){function a(){c=setInterval(function(){b?$("#drag-and-drop-overlay").fadeIn(500):($("#drag-and-drop-overlay").fadeOut(500),b=null,clearInterval(c))},64)}var d=document.body,b=null,c=0;d.ondragover=function(){null!==b&&void 0!==b||a();b=!0;return!1};d.ondragleave=function(){return b=!1};d.ondrop=function(c){null!==c.preventDefault&&c.preventDefault();b=!1;a();var d=c.dataTransfer.files[0];if(void 0!==d){if(!0==={"image/png":!0,"image/jpeg":!0,"image/gif":!0,"image/svg+xml":!0}[d.type]){c=
new FormData;c.append("file",d);var d=metahill.main.makeImageTagFromUrl("http://metahill.com/img/loading.gif"),k=metahill.main.makeEntryImage(metahill.main.userName,d,(new Date).getTime());$("#chat-entries").append(k);var h=new XMLHttpRequest;h.open("POST","php/image-upload.php");h.onload=function(){if(200==h.status){var a=h.getResponseHeader("Content-Description");console.log("all done: "+h.status+":"+a);k.remove();metahill.chat.sendImage(a,metahill.main.userId,metahill.main.userName,metahill.main.activeRoom.attr("data-roomid"),
metahill.helper.getSimpleText(metahill.main.activeRoom))}else console.log("Something went terribly wrong..."+h.status+":"+h.statusText)};h.send(c)}return!1}}});$(function(){var a=[];a.push("<b>Share images</b> by dragging them in the chat.");a.push("Don't want to miss anything? View the chat logs.");a.push("Put your message within * to make it <i>italics</i>.");a.push("Put your message within ** to make it <b>bold</b>.");a.push("Put your message within ` to make it <code>code</code>.");a.push("<b>metahill</b> is a non-for-profit service.");a.push("Join <b>@metahill</b> for metahill-questions &amp; feedback.");a.push('We visualize over 25 smilies. View the <a href="help/index.php?tab=messages&anchor=smilies" target="_blank">list</a>.');
a.push("Hold and drag rooms to change their order.");a.push("Be nice to your mates and keep the overall atmosphere nice. :)");setTimeout(function(){setInterval(function(){if(metahill.modals.preferences.enable_tips&&metahill.chat.isOnline){var d=a[Math.floor(Math.random()*a.length)];metahill.main.setCurrentStatus(d,"alert-info",1E4)}},6E5)},6E5)});metahill.log={};metahill.log.messages={};metahill.log.users={};metahill.log.times={};metahill.log.roomAttendees={};metahill.main={};
$(function(){function a(){var a=$("#channels-list").children();a.each(function(b,d){d=$(d);var n=d.find("button > .room-close");n.click(function(){g(n)});b===a.length-1&&c(d)})}function d(){$("#channels-list").children().each(function(a,b){b=$(b);b.click(function(){c(b)});b.children("button").each(function(a,l){$(l).click(function(){g(l)})})});$("#view-log-button").click(function(){$(this);document.location="log/"+encodeURIComponent(metahill.helper.getSimpleText(metahill.main.activeRoom))});$("#help-button").click(function(){document.location=
"help"});$("#submit-message").keydown(p);$("#add-new-room").click(function(){$("#add-new-room-rooms").children().each(function(a,b){$(b).click(function(){metahill.main.onNewRoomClicked(b)})})})}function b(a){var b=metahill.helper.getSimpleText(metahill.main.activeRoom),b=metahill.log.roomAttendees[b],c=a.split(" ").pop();a=a.replace(/\w+$/,"");if(""===c)return a;var d={};try{var e=c.toLowerCase();b.forEach(function(a){if(0===a.userName.toLowerCase().indexOf(e))throw c=a.userName+" ",d;})}catch(f){if(f!==
d)throw f;}return a+c}function c(a){if(m)m=!1;else if(void 0===metahill.main.activeRoom&&(metahill.main.activeRoom=$(document.createElement("span"))),a=$(a),"add-new-room"!==a.attr("id")){metahill.main.enableInput();var b=metahill.helper.getSimpleText(metahill.main.activeRoom),c=metahill.helper.getSimpleText(a);void 0===metahill.log.roomAttendees[c]&&(metahill.log.roomAttendees[c]=[]);c!==b&&(e(metahill.main.activeRoom),e(a),a.addClass("btn-primary"),metahill.main.activeRoom.addClass("room-favorite"),
metahill.main.activeRoom=a,metahill.main.updateChatBox(),metahill.main.updateAttendeesList(),$("#chat-header-topic").html(metahill.formatMessages.makeLinksClickable(metahill.helper.htmlEncode(a.attr("data-topic")))),a.attr("data-owner")===metahill.main.userId?0===$("#room-settings").length&&$("#view-log-button").after('<button class="btn" id="room-settings" style="font-family: inherit;" href="#modal-room-pref" data-toggle="modal"><img src="img/icon/room_settings.png" />Room settings</button>'):$("#room-settings").remove(),
a=a.children(".unseen-messages"),a.hide("slow"),a.text("0"))}}function e(a){a.removeClass("btn-warning btn-danger btn-primary btn-info btn-success")}function g(a){m=!0;var b=$(a).parent();a=b.attr("data-roomid");var c=metahill.helper.getSimpleText(b),d=b.attr("data-topic"),e=b.attr("data-owner");metahill.helper.submitHttpRequest("remove-favorite.php",{userId:metahill.main.userId,roomId:a});metahill.base.support.isChrome||metahill.base.support.isFirefox||metahill.base.support.isOpera?(b.css("maxHeight",
b.height()),b.animate({width:"0","padding-left":"0","padding-right":"0"},200,"swing",function(){b.remove()})):b.remove();var f=metahill.helper.getSimpleText(b)===metahill.helper.getSimpleText(metahill.main.activeRoom);(1>=b.parent().children().length||f)&&metahill.main.disableInput();h(a,c,d,e);metahill.chat.sendUserQuit(a,c);delete metahill.log.roomAttendees[c]}function k(a){var b=a.css("padding-left"),c=a.width();a.css("maxHeight",a.height());a.width(0);a.css("padding-left",0);a.css("padding-right",
0);a.show();a.animate({width:c,"padding-left":b,"padding-right":b},200,function(){a.removeAttr("style")})}function h(a,b,c,d){var e=$("#add-new-room-popover > div:nth-child(2) ul"),f=$(document.createElement("li")).addClass("ui-bootstrap-list-item btn room-favorite").attr("data-roomid",a).attr("data-topic",c).attr("data-owner",d).text(b);f.click(function(){metahill.main.onNewRoomClicked(f[0])});e.prepend(f)}function f(a,b,c){var d="";-1!==["server"].indexOf(a)&&(d="server-message");a===metahill.main.userName&&
(a="<b>"+a+"&nbsp;</b>");return'<div class="chat-entry '+d+'"><span class="chat-entry-options">'+metahill.helper.toHHMMSS(c)+'</span><span class="chat-entry-user ">&nbsp;'+a+'</span><span class="chat-entry-message">'+b+"</div>"}metahill.main.userName=$("#user-name > button").text().trim();metahill.main.userId=$("#user-id").html();$(document).ready(function(){a();d()});metahill.main.isStatusPersistent=!1;metahill.main.setCurrentStatus=function(a,b,c){c=void 0===c?5E3:c;var d=$("#site-status");"-50px"!==
d.css("margin-top")?d.animate({"margin-top":"-50px"},1E3,function(c,d,e){metahill.main.setCurrentStatus(a,b,e)}):(d.removeClass("alert-warning alert-error alert-info alert-success"),d.addClass(b),d.html(a),d.animate({"margin-top":"20px"},1E3),setTimeout(function(){metahill.main.isStatusPersistent||d.animate({"margin-top":"-50px"},1E3)},c))};metahill.main.makeAttendeeEntry=function(a,b){return'<li id="channel-attendees-'+a+'"><button disabled class="btn">'+b+"</button></li>"};var p=function(a){var c=
$("#submit-message"),d=[],e=-1,f;return function(a){switch(a.which){case 13:q()&&(a=metahill.helper.htmlEncode(c.val()).trim(),0<a.length&&(500<a.length&&(a=a.substr(0,500)),metahill.chat.sendMessage(a,metahill.main.userId,metahill.main.userName,metahill.main.activeRoom.attr("data-roomid"),metahill.helper.getSimpleText(metahill.main.activeRoom)),c.val(""),d.unshift(a),e=-1));break;case 9:var l=c.val();""!==l&&(a.preventDefault(),c.val(b(l)));break;case 38:-1===e&&(f=c.val());e<d.length-1&&(e++,c.val(d[e]));
break;case 40:e--,-1>=e?(c.val(f),e=-1):c.val(d[e])}}}(),r=function(){var a=RegExp(".*[\\s:;.,|<>]?"+metahill.main.userName+"[\\s:;.,!|<>]?.*","g");return function(b){return a.test(b)}}();metahill.main.logChatMessage=function(a,b,c,d){void 0===metahill.log.messages[a]&&(metahill.log.messages[a]=[]);void 0===metahill.log.users[a]&&(metahill.log.users[a]=[]);void 0===metahill.log.times[a]&&(metahill.log.times[a]=[]);metahill.log.messages[a].push(c);metahill.log.users[a].push(b);metahill.log.times[a].push(d)};
metahill.main.addVisibleMessage=function(a,b,c,d,e){metahill.main.logChatMessage(b,a,c,d);b!==metahill.helper.getSimpleText(metahill.main.activeRoom)?(b=$("#channels-list").find('li:contains("'+b+'")'),""!==a&&(r(c)?(metahill.sound.playUserAddressed(),$.titleAlert("Someone talked to you!"),b.removeClass("room-favorite"),b.addClass("btn-danger")):(a=b.children(".unseen-messages"),c=parseInt(a.text(),10),0===c&&a.show("slow"),a.text(c+1)))):(a=!0===e?$(metahill.main.makeEntryImageText(a,c,d)):$(metahill.main.makeEntryMessageText(a,
c,d)),c=$("#chat-entries"),c.append(a),c.animate({scrollTop:c.scrollTop()+500},100),a=a.children(),c=$(a[2]).height(),$(a[0]).height(c),$(a[1]).height(c),metahill.modals.liveUpdateChatTextSize())};metahill.main.makeImageTagFromUrl=function(a){return'<span class="image-tooltip"><img src="'+a+'"></img><span><img src="'+a+'"></img></span></span>'};metahill.main.addVisibleImage=function(a,b,c,d){c=metahill.main.makeImageTagFromUrl(c);metahill.main.addVisibleMessage(a,b,c,d,!0)};metahill.main.updateChatBox=
function(){var a=$("#chat-entries");a.empty();var c=metahill.helper.getSimpleText(metahill.main.activeRoom);if(void 0!==metahill.log.messages[c]){for(var b=metahill.log.messages[c].length,d="",e=0;e<b;++e){var f=metahill.log.users[c][e];f==metahill.main.userName&&(f="<b>"+f+"</b>");d+=metahill.main.makeEntryMessageText(f,metahill.log.messages[c][e],metahill.log.times[c][e])}a.append(d);metahill.modals.liveUpdateChatTextSize();$(window).resize();a.scrollTop(a.height())}};metahill.main.updateAttendeesList=
function(){var a=metahill.helper.getSimpleText(metahill.main.activeRoom);if(void 0!==metahill.log.roomAttendees[a]){var c=$("#channel-attendees-entries");c.empty();for(var a=metahill.log.roomAttendees[a],b="",d=0;d<a.length;++d)var e=a[d],b=b+metahill.main.makeAttendeeEntry(e.userId,e.userName);c.append(b)}};var m=!1;metahill.main.onNewRoomClicked=function(a){metahill.main.enableInput();var c=$(a),b=c.text();a=c.attr("data-roomid");var d=c.attr("data-topic"),e=c.attr("data-owner");metahill.helper.submitHttpRequest("add-favorite.php",
{userId:metahill.main.userId,roomId:a});metahill.chat.sendUserJoin(a,b);void 0!==metahill.main.activeRoom&&metahill.main.activeRoom.removeClass("btn-primary");$("#chat-header-topic").html(metahill.formatMessages.makeLinksClickable(d));$("#chat-entries").empty();a=metahill.main.openRoom(a,b,d,e);var d=$("#add-new-room").next(),e=parseInt(d.css("left"),10),f=a.width(),g=a.css("padding-left"),f=f+2*parseInt(g,10)+6;d.animate({left:e+f},200);(metahill.base.support.isChrome||metahill.base.support.isFirefox||
metahill.base.support.isOpera)&&k(a);c.animate({height:0,"padding-top":0,"padding-bottom":0},200,function(){c.remove();$('#add-new-room-popover > div:nth-child(2) ul > li:contains("'+b+'")').remove()});metahill.main.activeRoom=a};metahill.main.openRoom=function(a,b,d,e){var f=$('<li class="btn btn-primary room-favorite"/>');f.attr("data-roomid",a);f.attr("data-topic",d);f.attr("data-owner",e);f.text(b);c(f);f.click(function(){c(f)});var k=$('<button class="close room-close" style="margin-top:-2px;">&times;</button>');
a=$('<span class="unseen-messages"></span>');k.click(function(){g(k[0])});f.append(k);f.append(a);$("#channels-list").append(f);return f};metahill.main.enableInput=function(){var a=$("#submit-message");$("#chat-entries").removeAttr("disabled");a.removeAttr("disabled");a.focus();$("#view-log-button").show();$("#room-settings").show()};metahill.main.disableInput=function(){var a=$("#submit-message");$("#chat-entries").attr("disabled","disabled");a.attr("disabled","disabled");a.blur();$("#chat-header-topic").text("");
$("#view-log-button").hide();$("#room-settings").hide()};var q=function(){var a=[];return function(){a.push((new Date).getTime());if(3<a.length&&(a.shift(),!(3E3<a[2]-a[0]))){var c=$("#submit-status");c.is(":visible")||(c.removeClass(),c.empty(),c.addClass("alert alert-error"),c.append("<h4>Man, calm down!</h4>"),c.append("Your mission is not to spam the room. :P").hide().show("slow"),setTimeout(function(){c.hide("quick")},5E3));return!1}return!0}}();metahill.main.makeEntryMessageText=function(a,
c,b){c=metahill.formatMessages.styleMessage(c);return f(a,c,b)};metahill.main.makeEntryImageText=function(a,c,b){return f(a,c,b)}});metahill.modals={};
$(document).ready(function(){metahill.modals.preferences={};metahill.modals.preferences.enable_smilies=$("#modals-pref-enable-smilies").prop("checked");metahill.modals.preferences.enable_formatting=$("#modals-pref-enable-formatting").prop("checked");metahill.modals.preferences.enable_notification_sounds=$("#modals-pref-enable-notification-sounds").prop("checked");metahill.modals.preferences.chat_show_traffic=$("#modals-pref-chat-show-traffic").prop("checked");metahill.modals.preferences.chat_text_size=$("#modals-pref-textsize").val();
metahill.modals.preferences.chat_text_font=$("#modals-pref-font").val();metahill.modals.preferences.enable_tips=$("#modals-pref-enable-tips").val();metahill.modals.preferences.user_id=metahill.main.userId;metahill.modals.liveUpdateChatTextSize();metahill.modals.liveUpdateFont();$("#modals-profile-current-password-info, #modals-room-pref-current-password-info").popover({trigger:"hover",placement:"left",title:"Why do you want my password?",content:"Security. It is all about confidential information which we try to keep as secure as possible."})});
metahill.modals.liveUpdateFont=function(){var a=$("#modals-pref-font option:selected").val();$("body *").css("font-family",a)};metahill.modals.liveUpdateChatTextSize=function(){var a=$("#modals-pref-textsize option:selected").text().replace(" ","");$("#chat-entries").css("font-size",a);var a=parseInt(a,10),d;d=16<=a?210:150;$(".chat-entry-user").css("width",d);a-=10;$("#chat .chat-entry > *").css("padding-top",a+"px").css("padding-bottom",a+"px");$(window).resize()};
$(function(){$("#modal-pref-submit").click(function(a){$("#modal-pref").modal("hide");metahill.helper.submitHttpRequest("update-preferences.php",metahill.modals.preferences)});$("#modals-pref-enable-smilies").change(function(){metahill.modals.preferences.enable_smilies=$(this).is(":checked");metahill.main.updateChatBox()});$("#modals-pref-enable-formatting").change(function(){metahill.modals.preferences.enable_formatting=$(this).is(":checked");metahill.main.updateChatBox()});$("#modals-pref-enable-notification-sounds").change(function(){metahill.modals.preferences.enable_notification_sounds=
$(this).is(":checked")});$("#modals-pref-textsize").change(function(){metahill.modals.preferences.chat_text_size=$(this).val();metahill.modals.liveUpdateChatTextSize()});$("#modals-pref-font").change(function(){metahill.modals.preferences.chat_text_font=$(this).val();metahill.modals.liveUpdateFont()});$("#modals-pref-chat-show-traffic").change(function(){metahill.modals.preferences.chat_show_traffic=$(this).is(":checked")});$("#modals-pref-enable-tips").change(function(){metahill.modals.preferences.enable_tips=
$(this).is(":checked")})});
$(function(){function a(a,c){metahill.helper.submitHttpRequest("update-profile.php",a,c)}var d=$("#modal-profile-submit");$("#modal-profile").on("shown",function(){$("#modals-profile-current-password").focus()});$("#modals-profile-current-password").bind("propertychange keyup input paste",function(){var a=$(this).val().length;8<=a&&20>=a?d.removeAttr("disabled"):d.prop("disabled",!0)});d.click(function(b){var c=$("#modals-profile-delete");b={};if(c.is(":checked"))confirm("If you confirm now, your account will be permanently removed and you will not be able to log in with this user again. Do you still want to confirm the account deletion?")?($("#modal-profile").modal("hide"),
b.intent="delete-account",b.userId=metahill.main.userId,b.currentPassword=$("#modals-profile-current-password"),a(b),document.location.href="why-account-deletion.php"):c.prop("checked",!1);else{$("#modal-profile").modal("hide");var c=$("#modals-profile-current-password"),d=$("#modals-profile-new-password");b.intent="change-password";b.userId=metahill.main.userId;b.currentPassword=c.val();b.newPassword=d.val();c.val("");d.val("");a(b,function(a){var c=a.split(">");a=c[0];c=parseInt(c[1],10);switch(a){case "delete-account":break;
case "change-password":1===parseInt(c,10)?metahill.main.setCurrentStatus("Password changed successfully.","alert-success"):metahill.main.setCurrentStatus("Sorry man, I couldn't verify that password.","alert-warning");break;default:console.log("unknown intent returned")}})}})});
$(function(){function a(a,b){metahill.helper.submitHttpRequest("update-new-room.php",a,b)}function d(){b.isNameLengthOk&&b.isTopicLengthOk&&b.isNameAvailable?$("#modal-new-room-submit").removeAttr("disabled"):$("#modal-new-room-submit").prop("disabled",!0)}$("#modal-new-room").on("show",function(){$("#add-new-room").popover("hide")});$("#modal-new-room").on("shown",function(){$("#modals-new-room-name").focus()});var b={isNameAvailable:!1,isNameLengthOk:!1,isTopicLengthOk:!1};$("#modals-new-room-name").bind("propertychange keyup input paste",
function(){var a=$(this).val().trim(),e=a.length;b.isNameLengthOk=3<=e&&20>=e;b.isNameLengthOk&&(e={},e.roomname=a,metahill.helper.submitHttpRequest("does-roomname-exist.php",e,function(a){1===parseInt(a,10)?(b.isNameAvailable=!1,$("#modals-new-room-name-status").show()):(b.isNameAvailable=!0,$("#modals-new-room-name-status").hide());d()}));d()});$("#modals-new-room-topic").bind("propertychange keyup input paste",function(){var a=$(this).val().trim().length;b.isTopicLengthOk=20<=a&&200>=a;d()});$("#modal-new-room-submit").click(function(c){$("#modal-new-room").modal("hide");
var b={};b.name=$("#modals-new-room-name").val().trim();b.owner=metahill.main.userId;b.topic=$("#modals-new-room-topic").val().trim();a(b,function(a){$("#modals-new-room-name").val("");$("#modals-new-room-topic").val("");metahill.main.openRoom(a,b.name,b.topic);metahill.chat.sendUserJoin(a,b.name);metahill.chat.sendMessage("You just created the room <b>"+b.name+"</b>, congratulations!",-1,"server",a,b.name);var c={};c.userId=b.owner;c.roomId=a;metahill.helper.submitHttpRequest("add-favorite.php",
c)})})});
$(function(){function a(a,b){metahill.helper.submitHttpRequest("update-room-pref.php",a,b)}function d(){var a=b.isTopicLengthOk;$("#modals-room-pref-delete").is(":checked")&&(a=!0);b.isPasswordLengthOk&&a?$("#modal-room-pref-submit").removeAttr("disabled"):$("#modal-room-pref-submit").prop("disabled",!0)}var b={isRoomNameToTitleAdded:!1,isPasswordLengthOk:!1,isTopicLengthOk:!1,currentTopic:""};$("#modal-room-pref").on("show",function(){if(!b.isRoomNameToTitleAdded){b.isRoomNameToTitleAdded=!0;var a=
$("#modal-room-pref h3:first");a.html("<u>"+metahill.helper.getSimpleText(metahill.main.activeRoom)+"</u>"+a.html())}b.currentTopic=metahill.main.activeRoom.attr("data-topic");$("#modals-room-pref-topic").val(b.currentTopic).keyup()});$("#modal-room-pref").on("shown",function(){$("#modals-room-pref-topic").focus().val("").val(metahill.main.activeRoom.attr("data-topic"))});$("#modal-room-pref-submit").click(function(){var c=$("#modals-room-pref-current-password"),d=$(this),g={};g.roomTopic=$("#modals-room-pref-topic").val().trim();
g.roomId=metahill.main.activeRoom.attr("data-roomid");g.userId=metahill.main.userId;g.userPassword=c.val();g.roomTopic===b.currentTopic?($("#modal-room-pref").modal("hide"),c.val("")):a(g,function(a){c.val("");1<=parseInt(a,10)?(metahill.main.activeRoom.attr("data-topic",g.roomTopic),$("#chat-header-topic").html(metahill.formatMessages.makeLinksClickable(g.roomTopic)),$("#modal-room-pref").modal("hide")):(c.attr("placeholder","Wrong pass :("),c.focus(),d.prop("disabled",!0))})});$("#modals-room-pref-current-password").bind("propertychange keyup input paste",
function(){var a=$(this).val().trim().length;b.isPasswordLengthOk=8<=a&&30>=a;d()});$("#modals-room-pref-topic").bind("propertychange keyup input paste",function(){var a=$(this).val().trim().length;b.isTopicLengthOk=20<=a&&200>=a;d()})});$(function(){function a(){$("#chat-entries").children().each(function(a,b){var c=$(b).children(),e=$(c[2]).height();$(c[0]).height(e);$(c[1]).height(e)})}$(document).ready(function(){metahill.base.support.isMac?$("<style>.room-close{left:auto;right:20px;}.close{float:left;}</style>").appendTo("body"):metahill.base.support.isWindows&&$('<link rel="stylesheet" type="text/css" href="css/windows-fixes.css"/>').appendTo("head");$(window).resize(function(){var d=$("#submit-area"),b=$("#channel-attendees-entries"),
c=$("#channel-attendees"),e=$("header");return function(){a();var g=$(this).height()-e.height()-d.height()-90;b.height(g-53);c.height(g)}}())});$(".selectpicker").selectpicker();$("#add-new-room").popover({trigger:"click",html:!0,title:function(){return $("#add-new-room-title").html()},content:function(){return $("#add-new-room-content").html()}});$("body").on("click",function(a){$("#add-new-room").each(function(){$(this).is(a.target)||(0!==$(this).has(a.target).length||0!==$(".popover").has(a.target).length)||
$(this).popover("hide")})});$("#channels-list").sortable();$("#filter-search-user").filterList()});$(function(){WebFontConfig={google:{families:["Noto+Sans::latin","Noto+Serif::latin"]}};var a=document.createElement("script");a.src=("https:"==document.location.protocol?"https":"http")+"://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js";a.async="true";var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(a,d)});metahill.roomProposer={};$(document).ready(function(){$("#add-new-room").click(function(){metahill.roomProposer.addRoomSearcher($("#add-new-room-search"))})});metahill.roomProposer.getOpenRoomNames=function(){var a=[];$("#channels-list").children().each(function(d){a.push(metahill.helper.getSimpleText($(this)))});return a};
metahill.roomProposer.createHtmlChildren=function(a){var d=metahill.roomProposer.getOpenRoomNames();console.log(JSON.stringify(d));for(var b="",c=0;c<a.length;c++){var e=a[c];-1===$.inArray(e.name,d)&&(b+="<li class='ui-bootstrap-list-item btn' data-owner='"+e.owner+"'sn data-roomid='"+e.id+"' data-topic='"+e.topic+"'>"+e.name+"</li>")}""===b&&(b='<p class="btn" disabled>No rooms found :(</p>');return b};
metahill.roomProposer.addRoomSearcher=function(a){a.bind("propertychange keyup input paste",function(){var d=a.val();metahill.roomProposer.requestRoomsFromSearchTerm(d)})};metahill.roomProposer.requestRoomsFromSearchTerm=function(a){metahill.chat.connection.send(JSON.stringify({intent:"search-rooms",searchTerm:a}))};
metahill.roomProposer.handleIncomingSearchResults=function(a){a=metahill.roomProposer.createHtmlChildren(a);var d=$("#add-new-room-rooms");d.empty().append(a);d.children().each(function(a,c){$(c).click(function(){metahill.main.onNewRoomClicked(c)})})};metahill.roomProposer.requestRoomProposals=function(){metahill.chat.connection.send(JSON.stringify({intent:"room-proposals",userId:metahill.main.userId,userName:metahill.main.userName}))};
metahill.roomProposer.handleIncomingRoomProposals=function(a){a=metahill.roomProposer.createHtmlChildren(a);$("#add-new-room-rooms").append(a)};metahill.chat={};metahill.chat.connection={};
$(function(){function a(a,b){var c=new Date;metahill.modals.preferences.chat_show_traffic&&metahill.main.addVisibleMessage("",a,"_"+b+"_",c)}function d(){metahill.chat.connection=new WebSocket(b);metahill.chat.connection.onopen=e;metahill.chat.connection.onerror=g;metahill.chat.connection.onclose=k;metahill.chat.connection.onmessage=h}window.WebSocket=window.WebSocket||window.MozWebSocket;window.WebSocket||console.log($("<p>",{text:"Sorry, but your browser doesn't support WebSockets."}));var b="ws://127.0.0.1:1337",
c=metahill.chat.isOnline=!0,e=function(){c=metahill.chat.isOnline=!0;var a=[];$("#channels-list").children().each(function(b,c){var d=$(c);a.push({roomId:d.attr("data-roomid"),roomName:metahill.helper.getSimpleText(d)})});a.forEach(function(a){metahill.chat.sendUserJoin(a.roomId,a.roomName)});metahill.roomProposer.requestRoomProposals();metahill.main.enableInput();setTimeout(function(){metahill.main.isStatusPersistent=!1;metahill.main.setCurrentStatus("Welcome back!","alert-success")},1E3)},g=function(a){metahill.chat.isOnline=
!1;console.log("Sorry, but there's some problem with your connection or the server is down.</p>")},k=function(){metahill.chat.isOnline=!1;c&&(c=!1,metahill.main.disableInput(),metahill.log.roomAttendees={},$("#channel-attendees-entries").empty(),metahill.main.isStatusPersistent=!0,metahill.main.setCurrentStatus("Awwr. It seems we got a server problem. We're working on it...","alert-error",-1));setTimeout(function(){d();console.log("retry")},3E4)},h=function(b){console.log("message received: "+JSON.stringify(b.data));
b=JSON.parse(b.data);switch(b.intent){case "tell":metahill.main.addVisibleMessage(b.userName,b.roomName,b.content,b.time);break;case "tell-image":metahill.main.addVisibleImage(b.userName,b.roomName,b.content,b.time);break;case "attendees-list":metahill.chat.updateAttendeesList(b.attendees,b.roomId,b.roomName);break;case "quit-room":var c=b.userId,d=b.userName;b=b.roomName;console.log("userquit:"+c+" in "+b);if(void 0===metahill.log.roomAttendees[b])console.log("userquit with undefined roomName");
else{for(var e=0;e<metahill.log.roomAttendees[b].length;++e)metahill.log.roomAttendees[b][e].userId===c&&metahill.log.roomAttendees[b].remove(e);b===metahill.helper.getSimpleText(metahill.main.activeRoom)&&$("#channel-attendees-"+c).remove();a(b,d+" quit the room.")}break;case "join-room":c=b.userId;d=b.userName;b=b.roomName;console.log("userjoin:"+c+"="+d+" in "+b);void 0===metahill.log.roomAttendees[b]&&(metahill.log.roomAttendees[b]=[]);metahill.log.roomAttendees[b].push({userId:c,userName:d});
b===metahill.helper.getSimpleText(metahill.main.activeRoom)&&$("#channel-attendees-entries").append(metahill.main.makeAttendeeEntry(c,d));a(b,d+" joined the room.");break;case "room-proposals":metahill.roomProposer.handleIncomingRoomProposals(b.list);break;case "search-rooms":metahill.roomProposer.handleIncomingSearchResults(b.list,b.inputSource);break;default:console.log("Unknown `intent`.")}};d()});
metahill.chat.updateAttendeesList=function(a,d,b){d=$("#channel-attendees-entries");b===metahill.helper.getSimpleText(metahill.main.activeRoom)&&d.empty();void 0===metahill.log.roomAttendees[b]&&(metahill.log.roomAttendees[b]=[]);var c=b===metahill.helper.getSimpleText(metahill.main.activeRoom),e="";a.forEach(function(a){metahill.log.roomAttendees[b].push({userId:a.userId,userName:a.userName});c&&(e+=metahill.main.makeAttendeeEntry(a.userId,a.userName))});d.append(e)};
metahill.chat.sendUserQuit=function(a,d){metahill.chat.connection.send(JSON.stringify({intent:"quit-room",userId:metahill.main.userId,userName:metahill.main.userName,roomId:a,roomName:d}))};metahill.chat.sendUserJoin=function(a,d){metahill.chat.connection.send(JSON.stringify({intent:"join-room",userId:metahill.main.userId,userName:metahill.main.userName,roomId:a,roomName:d}))};
metahill.chat.sendMessage=function(a,d,b,c,e){metahill.chat.connection.send(JSON.stringify({content:a,intent:"tell",userId:d,userName:b,roomId:c,roomName:e}))};metahill.chat.sendImage=function(a,d,b,c,e){metahill.chat.connection.send(JSON.stringify({content:a,intent:"tell-image",userId:d,userName:b,roomId:c,roomName:e}))};
