var metahill=metahill||{};aoeu4={};aoeu4.support={};
$(function(){var a=navigator.userAgent.toLowerCase();aoeu4.support.isChrome=-1<a.indexOf("chrome");aoeu4.support.isOpera=-1<a.indexOf("opera");aoeu4.support.isFirefox=-1<a.indexOf("firefox");aoeu4.support.isInternetExplorer=-1<navigator.appName.indexOf("Microsoft")||-1<a.indexOf("msie");aoeu4.support.isMac=-1<navigator.platform.toLowerCase().indexOf("mac");aoeu4.support.isWindows=-1<navigator.appVersion.indexOf("Win");aoeu4.support.isInternetExplorer&&
-1===window.location.toString().indexOf("get-a-modern-browser")&&(window.location="http://www.metahill.com/get-a-modern-browser.php")});String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};String.prototype.ltrim=function(){return this.replace(/^\s+/,"")};String.prototype.rtrim=function(){return this.replace(/\s+$/,"")};Array.prototype.remove=function(a,d){var b=this.slice((d||a)+1||this.length);this.length=0>a?this.length+a:a;return this.push.apply(this,b)};metahill=metahill||{};aoeu1={};
aoeu1.submitHttpRequest=function(a,d,b){var c=new XMLHttpRequest;c.open("POST","php/"+a);c.onload=function(){if(200===c.status)console.log("http request: ok. "+c.responseText),void 0!==b&&b(c.getResponseHeader("Content-Description"));else{var a=c.getResponseHeader("Content-Description");console.log("http request: something went terribly wrong("+a+"), "+c.status+":"+c.statusText)}};a=new FormData;for(var e in d)a.append(e,d[e]);c.send(a)};
aoeu1.toHHMMSS=function(a){return(new Date(a)).toTimeString().replace(/.*(\d{2}:\d{2}:\d{2}).*/,"$1")};aoeu1.getSimpleText=function(a){return a.clone().children().remove().end().text().trim()};aoeu1.openUrlInNewTab=function(a){window.open(a,"_blank").focus()};aoeu1.getGetParameters=function(){for(var a=window.location.search.substr(1).split("&"),d={},b=0;b<a.length;b++){var c=a[b].split("=");d[c[0]]=c[1]}return d};aoeu1.htmlEncode=function(a){return $(document.createElement("div")).text(a).html()};
aoeu1.htmlDecode=function(a){return $(document.createElement("div")).html(a).text()};aoeu3={};aoeu3.playUserAddressed=function(){var a=new Audio("sound/user-addressed.wav");return function(){aoeu2.preferences.enable_notification_sounds&&a.play()}}();metahill=metahill||{};aoeu5={};
aoeu5.replaceTextSmilies=function(){function a(a){return a.replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1")}var d={":)":"smile.png",":-)":"smile.png","=)":"smile.png",":D":"biggrin.png",":-D":"biggrin.png","=D":"biggrin.png",";)":"wink.png",";D":"wink.png",";-)":"wink.png",";-D":"wink.png",":?":"confused.png",":-?":"confused.png",":(":"sad.png",":-(":"sad.png",":'(":"crying.png",">.<":"pinch.png",">_<":"pinch.png","=8-)":"cool.png",":S":"unsure.png",":s":"unsure.png","^^":"squint.png","<3":"love.png"},
b={":angry":"angry.png",":biggrin":"biggrin.png",":blink":"blink.png",":confused":"confused.png",":cool":"cool.png",":crying":"crying.png",":cursing":"cursing.png",":evil":"evil.png",":huh":"huh.png",":love":"love.png",":mellow":"mellow.png",":pinch":"pinch.png",":rolleyes":"rolleyes.png",":sad":"sad.png",":sleeping":"sleeping.png",":smile":"smile.png",":squint":"squint.png",":thumbdown":"thumbdown.png",":thumbsup":"thumbsup.png",":thumbup":"thumbup.png",":tongue":"tongue.png",":unsure":"unsure.png",
":w00t":"w00t.png",":wacko":"wacko.png",":whistling":"whistling.png",":wink":"wink.png"};return function(c){if(!aoeu2.preferences.enable_smilies)return c;Object.keys(b).forEach(function(e){var d='<img src="img/smilies/'+b[e]+'"></img>';-1!==c.indexOf(e)&&(e=RegExp("("+a(e)+")(?=(?:(?:[^`]*`){2})*[^`]*$)","g"),c=c.replace(e,d))});Object.keys(d).forEach(function(b){var g='<img src="img/smilies/'+d[b]+'"></img>';-1!==c.indexOf(b)&&(b=RegExp("("+a(b)+")(?=(?:(?:[^`]*`){2})*[^`]*$)","g"),c=c.replace(b,
g))});return c}}();aoeu5.boldItalicsCode=function(a){if(!aoeu2.preferences.enable_formatting)return a;a=a.replace(/(\*[^`]+\*|`[^`]+`)/g,function(a,b){return"*"===b[0]?b.replace(/^\*(.*)\*$/,"<strong>$1</strong>"):b});a=a.replace(/(_[^`]+_|`[^`]+`)/g,function(a,b){return"_"===b[0]?b.replace(/^_(.*)_$/,"<em>$1</em>"):b});return a=a.replace(/`(.+?)`/g,"<code>$1</code>")};
aoeu5.styleMessage=function(a,d){a=aoeu5.makeLinksClickable(a);a=aoeu5.replaceTextSmilies(a);return a=aoeu5.boldItalicsCode(a)};
aoeu5.makeLinksClickable=function(a){function d(a){a=a.replace(/_/g,"%5f");return 0===a.indexOf("http")?'<a target="_blank" href="'+a+'">'+a+"</a>":'<a target="_blank" href="http://'+a+'">'+a+"</a>"}var b=/((http:\/\/|www)[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/gi;return function(a){return null===a||void 0===a?"":a.replace(b,d)}}();$(function(){function a(){c=setInterval(function(){b?$("#drag-and-drop-overlay").fadeIn(500):($("#drag-and-drop-overlay").fadeOut(500),b=null,clearInterval(c))},64)}var d=document.body,b=null,c=0;d.ondragover=function(){null!==b&&void 0!==b||a();b=!0;return!1};d.ondragleave=function(){return b=!1};d.ondrop=function(c){null!==c.preventDefault&&c.preventDefault();b=!1;a();var d=c.dataTransfer.files[0];if(void 0!==d){if(!0==={"image/png":!0,"image/jpeg":!0,"image/gif":!0,"image/svg+xml":!0}[d.type]){c=
new FormData;c.append("file",d);var d=aoeu6.makeImageTagFromUrl("http://metahill.com/img/loading.gif"),k=$(aoeu6.makeEntryImageText(aoeu6.userName,d,(new Date).getTime()));$("#chat-entries").append(k);var h=new XMLHttpRequest;h.open("POST","php/image-upload.php");h.onload=function(){if(200==h.status){var a=h.getResponseHeader("Content-Description");console.log("all done: "+h.status+":"+a);k.remove();aoeu7.sendImage(a,aoeu6.userId,aoeu6.userName,aoeu6.activeRoom.attr("data-roomid"),
aoeu1.getSimpleText(aoeu6.activeRoom))}else console.log("Something went terribly wrong..."+h.status+":"+h.statusText)};h.send(c)}return!1}}});$(function(){var a=[];a.push("<b>Share images</b> by dragging them in the chat.");a.push("Don't want to miss anything? View the chat logs.");a.push("Put your message within * to make it <i>italics</i>.");a.push("Put your message within ** to make it <b>bold</b>.");a.push("Put your message within ` to make it <code>code</code>.");a.push("<b>metahill</b> is a non-for-profit service.");a.push("Join <b>metahill</b> for metahill-questions &amp; feedback.");a.push('We visualize over 25 smilies. View the <a href="help/index.php?tab=messages&anchor=smilies" target="_blank">list</a>.');
a.push("Hold and drag rooms to change their order.");a.push("Be nice to your mates and keep the overall atmosphere nice. :)");setTimeout(function(){setInterval(function(){if(aoeu2.preferences.enable_tips&&aoeu7.isOnline){var d=a[Math.floor(Math.random()*a.length)];aoeu6.setCurrentStatus(d,"alert-info",1E4)}},6E5)},6E5)});aoeu9={};aoeu9.messages={};aoeu9.users={};aoeu9.times={};aoeu9.roomAttendees={};aoeu6={};
$(function(){function a(){var a=$("#channels-list").children();a.each(function(b,d){d=$(d);var e=d.find("button > .room-close");e.click(function(){g(e)});k(d);b===a.length-1&&c(d)})}function d(){$("#channels-list").children().each(function(a,b){b=$(b);b.click(function(){c(b)});b.children("button").each(function(a,m){$(m).click(function(){g(m)})})});$("#view-log-button").click(function(){$(this);document.location="log/"+encodeURIComponent(aoeu1.getSimpleText(aoeu6.activeRoom))});
$("#help-button").click(function(){document.location="help"});$("#submit-message").keydown(l);$("#add-new-room").click(function(){$("#add-new-room-rooms").children().each(function(a,b){$(b).click(function(){aoeu6.onNewRoomClicked(b)})})})}function b(a){var b=aoeu1.getSimpleText(aoeu6.activeRoom),b=aoeu9.roomAttendees[b],c=a.split(" ").pop();a=a.replace(/\w+$/,"");if(""===c)return a;var d={};try{var e=c.toLowerCase();b.forEach(function(a){if(0===a.userName.toLowerCase().indexOf(e))throw c=
a.userName+" ",d;})}catch(f){if(f!==d)throw f;}return a+c}function c(a){if(n)n=!1;else if(void 0===aoeu6.activeRoom&&(aoeu6.activeRoom=$(document.createElement("span"))),a=$(a),"add-new-room"!==a.attr("id")){aoeu6.enableInput();var b=aoeu1.getSimpleText(aoeu6.activeRoom),c=aoeu1.getSimpleText(a);void 0===aoeu9.roomAttendees[c]&&(aoeu9.roomAttendees[c]=[]);c!==b&&(e(aoeu6.activeRoom),e(a),a.addClass("btn-primary"),aoeu6.activeRoom.addClass("room-favorite"),
aoeu6.activeRoom=a,aoeu6.updateChatBox(),aoeu6.updateAttendeesList(),$("#chat-header-topic").html(aoeu5.makeLinksClickable(aoeu1.htmlEncode(a.attr("data-topic")))),a.attr("data-owner")===aoeu6.userId?0===$("#room-settings").length&&$("#view-log-button").after('<button class="btn" id="room-settings" alt="Room Settings" title="Room Settings"  style="font-family: inherit;" href="#modal-room-pref" data-toggle="modal"><img src="img/icon/room_settings.png" />Room Settings</button>'):
$("#room-settings").remove(),a=a.children(".unseen-messages"),a.hide("slow"),a.text("0"))}}function e(a){a.removeClass("btn-warning btn-danger btn-primary btn-info btn-success")}function g(a){n=!0;var b=$(a).parent();a=b.attr("data-roomid");var c=aoeu1.getSimpleText(b),d=b.attr("data-topic"),e=b.attr("data-owner");aoeu1.submitHttpRequest("remove-favorite.php",{position:b.index()+1,userId:aoeu6.userId,roomId:a});aoeu4.support.isChrome||aoeu4.support.isFirefox||
aoeu4.support.isOpera?(b.css("maxHeight",b.height()),b.animate({width:"0","padding-left":"0","padding-right":"0"},200,"swing",function(){b.remove()})):b.remove();var f=aoeu1.getSimpleText(b)===aoeu1.getSimpleText(aoeu6.activeRoom);(1>=b.parent().children().length||f)&&aoeu6.disableInput();h(a,c,d,e);aoeu7.sendUserQuit(a,c);delete aoeu9.roomAttendees[c]}function k(a){var b=a.css("padding-left"),c=a.width();a.css("maxHeight",a.height());a.width(0);
a.css("padding-left",0);a.css("padding-right",0);a.show();a.animate({width:c,"padding-left":b,"padding-right":b},200,function(){a.removeAttr("style")})}function h(a,b,c,d){var e=$("#add-new-room-popover > div:nth-child(2) ul"),f=$(document.createElement("li")).addClass("ui-bootstrap-list-item btn room-favorite").attr("data-roomid",a).attr("data-topic",c).attr("data-owner",d).text(b);f.click(function(){aoeu6.onNewRoomClicked(f[0])});e.prepend(f)}function f(a,b,c){var d="";-1!==["server"].indexOf(a)&&
(d="server-message");a===aoeu6.userName&&(a="<b>"+a+"&nbsp;</b>");return'<div class="chat-entry '+d+'"><span class="chat-entry-options">'+aoeu1.toHHMMSS(c)+'</span><span class="chat-entry-user ">&nbsp;'+a+'</span><span class="chat-entry-message">'+b+"</div>"}aoeu6.userName=$("#user-name > button").text().trim();aoeu6.userId=$("#user-id").html();$(document).ready(function(){a();d()});aoeu6.isStatusPersistent=!1;aoeu6.setCurrentStatus=function(a,b,c){c=
void 0===c?5E3:c;var d=$("#site-status");"-50px"!==d.css("margin-top")?d.animate({"margin-top":"-50px"},500,function(c,d,e){aoeu6.setCurrentStatus(a,b,e)}):(d.removeClass("alert-warning alert-error alert-info alert-success"),d.addClass(b),d.html(a),d.animate({"margin-top":"20px"},500),setTimeout(function(){aoeu6.isStatusPersistent||d.animate({"margin-top":"-50px"},500)},c))};aoeu6.makeAttendeeEntry=function(a,b){return'<li id="channel-attendees-'+a+'"><button disabled class="btn">'+
b+"</button></li>"};var l=function(a){var c=$("#submit-message"),d=[],e=-1,f;return function(a){switch(a.which){case 13:p()&&(a=aoeu1.htmlEncode(c.val()).trim(),0<a.length&&(500<a.length&&(a=a.substr(0,500)),aoeu7.sendMessage(a,aoeu6.userId,aoeu6.userName,aoeu6.activeRoom.attr("data-roomid"),aoeu1.getSimpleText(aoeu6.activeRoom)),c.val(""),d.unshift(a),e=-1));break;case 9:var m=c.val();""!==m&&(a.preventDefault(),c.val(b(m)));break;case 38:-1===
e&&(f=c.val());e<d.length-1&&(e++,c.val(d[e]));break;case 40:e--,-1>=e?(c.val(f),e=-1):c.val(d[e])}}}(),q=function(){var a=RegExp(".*[\\s:;.,|<>]?"+aoeu6.userName+"[\\s:;.,!|<>]?.*","g");return function(b){return a.test(b)}}();aoeu6.logChatMessage=function(a,b,c,d){void 0===aoeu9.messages[a]&&(aoeu9.messages[a]=[]);void 0===aoeu9.users[a]&&(aoeu9.users[a]=[]);void 0===aoeu9.times[a]&&(aoeu9.times[a]=[]);aoeu9.messages[a].push(c);aoeu9.users[a].push(b);
aoeu9.times[a].push(d)};aoeu6.addVisibleMessage=function(a,b,c,d,e){aoeu6.logChatMessage(b,a,c,d);b!==aoeu1.getSimpleText(aoeu6.activeRoom)?(b=$("#channels-list").find('li:contains("'+b+'")'),""!==a&&(q(c)?(aoeu3.playUserAddressed(),$.titleAlert("Someone talked to you!"),b.removeClass("room-favorite"),b.addClass("btn-danger")):(a=b.children(".unseen-messages"),c=parseInt(a.text(),10),0===c&&a.show("slow"),a.text(c+1)))):(a=!0===e?$(aoeu6.makeEntryImageText(a,
c,d)):$(aoeu6.makeEntryMessageText(a,c,d)),c=$("#chat-entries"),b=c[0].scrollHeight-c.scrollTop()===c.outerHeight(),c.append(a),b&&c.animate({scrollTop:c.scrollTop()+500},500),a=a.children(),c=$(a[2]).height(),$(a[0]).height(c),$(a[1]).height(c),aoeu2.liveUpdateChatTextSize())};aoeu6.makeImageTagFromUrl=function(a){return'<span class="image-tooltip"><img src="'+a+'"></img><span><img src="'+a+'"></img></span></span>'};aoeu6.addVisibleImage=function(a,b,c,d){c=aoeu6.makeImageTagFromUrl(c);
aoeu6.addVisibleMessage(a,b,c,d,!0)};aoeu6.updateChatBox=function(){var a=$("#chat-entries");a.empty();var b=aoeu1.getSimpleText(aoeu6.activeRoom);if(void 0!==aoeu9.messages[b]){for(var c=aoeu9.messages[b].length,d="",e=0;e<c;++e){var f=aoeu9.users[b][e];f==aoeu6.userName&&(f="<b>"+f+"</b>");d+=aoeu6.makeEntryMessageText(f,aoeu9.messages[b][e],aoeu9.times[b][e])}a.append(d);aoeu2.liveUpdateChatTextSize();
$(window).resize();a.scrollTop(a.height())}};aoeu6.updateAttendeesList=function(){var a=aoeu1.getSimpleText(aoeu6.activeRoom);if(void 0!==aoeu9.roomAttendees[a]){var b=$("#channel-attendees-entries");b.empty();for(var a=aoeu9.roomAttendees[a],c="",d=0;d<a.length;++d)var e=a[d],c=c+aoeu6.makeAttendeeEntry(e.userId,e.userName);b.append(c)}};var n=!1;aoeu6.onNewRoomClicked=function(a){aoeu6.enableInput();var b=$(a),c=b.text();a=b.attr("data-roomid");
var d=b.attr("data-topic"),e=b.attr("data-owner");aoeu1.submitHttpRequest("add-favorite.php",{userId:aoeu6.userId,roomId:a,position:$("#channels-list").children().length+1});aoeu7.sendUserJoin(a,c);void 0!==aoeu6.activeRoom&&aoeu6.activeRoom.removeClass("btn-primary");$("#chat-header-topic").html(aoeu5.makeLinksClickable(d));$("#chat-entries").empty();a=aoeu6.openRoom(a,c,d,e);var d=$("#add-new-room").next(),e=parseInt(d.css("left"),
10),f=a.width(),g=a.css("padding-left"),f=f+2*parseInt(g,10)+6;d.animate({left:e+f},200);(aoeu4.support.isChrome||aoeu4.support.isFirefox||aoeu4.support.isOpera)&&k(a);b.animate({height:0,"padding-top":0,"padding-bottom":0},200,function(){b.remove();$('#add-new-room-popover > div:nth-child(2) ul > li:contains("'+c+'")').remove()});aoeu6.activeRoom=a};aoeu6.openRoom=function(a,b,d,e){var f=$('<li class="btn btn-primary room-favorite"/>');f.attr("data-roomid",
a);f.attr("data-topic",d);f.attr("data-owner",e);f.text(b);c(f);f.click(function(){c(f)});var k=$('<button class="close room-close">&times;</button>');a=$('<span class="unseen-messages"></span>');k.click(function(){g(k[0])});f.append(k);f.append(a);$("#channels-list").append(f);return f};aoeu6.enableInput=function(){var a=$("#submit-message");$("#chat-entries").removeAttr("disabled");a.removeAttr("disabled");a.focus();$("#view-log-button").show();$("#room-settings").show()};aoeu6.disableInput=
function(){var a=$("#submit-message");$("#chat-entries").attr("disabled","disabled");a.attr("disabled","disabled");a.blur();$("#chat-header-topic").text("");$("#view-log-button").hide();$("#room-settings").hide()};var p=function(){var a=[];return function(){a.push((new Date).getTime());if(3<a.length&&(a.shift(),!(3E3<a[2]-a[0]))){var b=$("#submit-status");120===parseInt(b.css("marginTop"),10)&&(b.removeClass(),b.empty(),b.addClass("alert alert-error"),b.append("<h1>Man, calm down!</h1>"),b.append("Your mission is not to spam the room. :P"),
b.animate({"margin-top":"40px"},500),setTimeout(function(){b.animate({"margin-top":"120px"},500)},5E3));return!1}return!0}}();aoeu6.makeEntryMessageText=function(a,b,c){b=aoeu5.styleMessage(b);return f(a,b,c)};aoeu6.makeEntryImageText=function(a,b,c){return f(a,b,c)}});aoeu2={};
$(document).ready(function(){aoeu2.preferences={};aoeu2.preferences.enable_smilies=$("#modals-pref-enable-smilies").prop("checked");aoeu2.preferences.enable_formatting=$("#modals-pref-enable-formatting").prop("checked");aoeu2.preferences.enable_notification_sounds=$("#modals-pref-enable-notification-sounds").prop("checked");aoeu2.preferences.chat_show_traffic=$("#modals-pref-chat-show-traffic").prop("checked");aoeu2.preferences.chat_text_size=$("#modals-pref-textsize").val();
aoeu2.preferences.chat_text_font=$("#modals-pref-font").val();aoeu2.preferences.enable_tips=$("#modals-pref-enable-tips").val();aoeu2.preferences.user_id=aoeu6.userId;aoeu2.liveUpdateChatTextSize();$("#modals-profile-current-password-info, #modals-room-pref-current-password-info").popover({trigger:"hover",placement:"left",title:"Why do you want my password?",content:"Security. It is all about confidential information which we try to keep as secure as possible."})});
aoeu2.liveUpdateFont=function(){var a=$("#modals-pref-font option:selected").val();$("body *").css("font-family",a);$("#phpcss").remove()};aoeu2.liveUpdateChatTextSize=function(){var a=$("#modals-pref-textsize option:selected").text().replace(" ","");$("#chat-entries").css("font-size",a);var a=parseInt(a,10),d;d=16<=a?210:150;$(".chat-entry-user").css("width",d);a-=10;$("#chat .chat-entry").children().css("padding-top",a+"px").css("padding-bottom",a+"px");$(window).resize()};
$(function(){$("#modal-pref-submit").click(function(){$("#modal-pref").modal("hide");aoeu1.submitHttpRequest("update-preferences.php",aoeu2.preferences)});$("#modal-pref").on("hidden",function(){$("#submit-message").focus()});$("#modals-pref-enable-smilies").change(function(){aoeu2.preferences.enable_smilies=$(this).is(":checked");aoeu6.updateChatBox()});$("#modals-pref-enable-formatting").change(function(){aoeu2.preferences.enable_formatting=$(this).is(":checked");
aoeu6.updateChatBox()});$("#modals-pref-enable-notification-sounds").change(function(){aoeu2.preferences.enable_notification_sounds=$(this).is(":checked")});$("#modals-pref-textsize").change(function(){aoeu2.preferences.chat_text_size=$(this).val();aoeu2.liveUpdateChatTextSize()});$("#modals-pref-font").change(function(){aoeu2.preferences.chat_text_font=$(this).val();aoeu2.liveUpdateFont()});$("#modals-pref-chat-show-traffic").change(function(){aoeu2.preferences.chat_show_traffic=
$(this).is(":checked")});$("#modals-pref-enable-tips").change(function(){aoeu2.preferences.enable_tips=$(this).is(":checked")})});
$(function(){function a(a,c){aoeu1.submitHttpRequest("update-profile.php",a,c)}var d=$("#modal-profile-submit");$("#modal-profile").on("shown",function(){$("#modals-profile-current-password").focus()});$("#modal-profile").on("hidden",function(){$("#submit-message").focus()});$("#modals-profile-current-password").bind("propertychange keyup input paste",function(){var a=$(this).val().length;8<=a&&20>=a?d.removeAttr("disabled"):d.prop("disabled",!0)});d.click(function(b){var c=$("#modals-profile-delete");
b={};if(c.is(":checked"))confirm("If you confirm now, your account will be permanently removed and you will not be able to log in with this user again. Do you still want to confirm the account deletion?")?($("#modal-profile").modal("hide"),b.intent="delete-account",b.userId=aoeu6.userId,b.currentPassword=$("#modals-profile-current-password"),a(b),document.location.href="why-account-deletion.php"):c.prop("checked",!1);else{$("#modal-profile").modal("hide");var c=$("#modals-profile-current-password"),
d=$("#modals-profile-new-password");b.intent="change-password";b.userId=aoeu6.userId;b.currentPassword=c.val();b.newPassword=d.val();c.val("");d.val("");a(b,function(a){var b=a.split(">");a=b[0];b=parseInt(b[1],10);switch(a){case "delete-account":break;case "change-password":1===parseInt(b,10)?aoeu6.setCurrentStatus("Password changed successfully.","alert-success"):aoeu6.setCurrentStatus("Sorry man, I couldn't verify that password.","alert-warning");break;default:console.log("unknown intent returned")}})}})});
$(function(){function a(a,b){aoeu1.submitHttpRequest("update-new-room.php",a,b)}function d(){b.isNameLengthOk&&b.isTopicLengthOk&&b.isNameAvailable?$("#modal-new-room-submit").removeAttr("disabled"):$("#modal-new-room-submit").prop("disabled",!0)}$("#modal-new-room").on("show",function(){$("#add-new-room").popover("hide")}).on("shown",function(){$("#modals-new-room-name").focus()}).on("hidden",function(){$("#submit-message").focus()});var b={isNameAvailable:!1,isNameLengthOk:!1,isTopicLengthOk:!1};
$("#modals-new-room-name").bind("propertychange keyup input paste",function(){var a=$(this).val().trim(),e=a.length;b.isNameLengthOk=3<=e&&20>=e;b.isNameLengthOk&&(e={},e.roomname=a,aoeu1.submitHttpRequest("does-roomname-exist.php",e,function(a){1===parseInt(a,10)?(b.isNameAvailable=!1,$("#modals-new-room-name-status").show()):(b.isNameAvailable=!0,$("#modals-new-room-name-status").hide());d()}));d()});$("#modals-new-room-topic").bind("propertychange keyup input paste",function(){var a=
$(this).val().trim().length;b.isTopicLengthOk=20<=a&&200>=a;d()});$("#modal-new-room-submit").click(function(b){$("#modal-new-room").modal("hide");var d={};d.name=$("#modals-new-room-name").val().trim();d.owner=aoeu6.userId;d.topic=$("#modals-new-room-topic").val().trim();a(d,function(a){$("#modals-new-room-name").val("");$("#modals-new-room-topic").val("");aoeu6.openRoom(a,d.name,d.topic);aoeu7.sendUserJoin(a,d.name);aoeu7.sendMessage("You just created the room <b>"+
d.name+"</b>, congratulations!",-1,"server",a,d.name);var b={};b.userId=d.owner;b.roomId=a;b.position=$("#channels-list").children().length+1;aoeu1.submitHttpRequest("add-favorite.php",b)})})});
$(function(){function a(a,b){aoeu1.submitHttpRequest("update-room-pref.php",a,b)}function d(){var a=b.isTopicLengthOk;$("#modals-room-pref-delete").is(":checked")&&(a=!0);b.isPasswordLengthOk&&a?$("#modal-room-pref-submit").removeAttr("disabled"):$("#modal-room-pref-submit").prop("disabled",!0)}var b={isRoomNameToTitleAdded:!1,isPasswordLengthOk:!1,isTopicLengthOk:!1,currentTopic:""};$("#modal-room-pref").on("show",function(){if(!b.isRoomNameToTitleAdded){b.isRoomNameToTitleAdded=!0;var a=
$("#modal-room-pref h3:first");a.html('"'+aoeu1.getSimpleText(aoeu6.activeRoom)+'"'+a.html())}b.currentTopic=aoeu6.activeRoom.attr("data-topic");$("#modals-room-pref-topic").val(b.currentTopic).keyup()}).on("hidden",function(){$("#submit-message").focus()});$("#modal-room-pref").on("shown",function(){$("#modals-room-pref-topic").focus().val("").val(aoeu6.activeRoom.attr("data-topic"))});$("#modal-room-pref-submit").click(function(){var c=$("#modals-room-pref-current-password"),
d=$(this),g={};g.roomTopic=$("#modals-room-pref-topic").val().trim();g.roomId=aoeu6.activeRoom.attr("data-roomid");g.userId=aoeu6.userId;g.userPassword=c.val();g.roomTopic===b.currentTopic?($("#modal-room-pref").modal("hide"),c.val("")):a(g,function(a){c.val("");1<=parseInt(a,10)?(aoeu6.activeRoom.attr("data-topic",g.roomTopic),$("#chat-header-topic").html(aoeu5.makeLinksClickable(g.roomTopic)),$("#modal-room-pref").modal("hide")):(c.attr("placeholder","Wrong pass :("),
c.focus(),d.prop("disabled",!0))})});$("#modals-room-pref-current-password").bind("propertychange keyup input paste",function(){var a=$(this).val().trim().length;b.isPasswordLengthOk=8<=a&&30>=a;d()});$("#modals-room-pref-topic").bind("propertychange keyup input paste",function(){var a=$(this).val().trim().length;b.isTopicLengthOk=20<=a&&200>=a;d()})});$(function(){function a(){$("#chat-entries").children().each(function(a,b){var c=$(b).children(),e=$(c[2]).height();$(c[0]).height(e);$(c[1]).height(e)})}$(document).ready(function(){aoeu4.support.isMac&&$("<style>.room-close{left:auto;right:20px;}.close{float:left;}</style>").appendTo("body");$(window).resize(function(){var d=$("#submit-area"),b=$("#channel-attendees-entries"),c=$("#channel-attendees"),e=$("#chat-entries"),g=$("header"),k=-1,h=-1;return function(){var f=$(window).height(),
l=$(window).width();h!==l&&(a(),h=l);k!==f&&(l=$(this).height()-g.height()-d.height()-90,b.height(l-53),c.height(l),e.height(l-50),k=f)}}())});$(".selectpicker").selectpicker();$("#add-new-room").popover({trigger:"click",html:!0,title:function(){return $("#add-new-room-title").html()},content:function(){return $("#add-new-room-content").html()}});$("body").on("click",function(a){$("#add-new-room").each(function(){$(this).is(a.target)||(0!==$(this).has(a.target).length||0!==$(".popover").has(a.target).length)||
$(this).popover("hide")})});$("#filter-search-user").filterList()});$(function(){var a=-1;$("#channels-list").sortable({start:function(d,b){a=b.item.index(0)},stop:function(d,b){var c=b.item.index(),e={};e.startPosition=a+1;e.endPosition=c+1;e.roomId=b.item.attr("data-roomid");e.userId=aoeu6.userId;aoeu1.submitHttpRequest("update-room-positions.php",e,function(a){console.log(a)})}})});aoeu8={};$(document).ready(function(){$("#add-new-room").click(function(){aoeu8.addRoomSearcher($("#add-new-room-search"))})});aoeu8.getOpenRoomNames=function(){var a=[];$("#channels-list").children().each(function(d){a.push(aoeu1.getSimpleText($(this)))});return a};
aoeu8.createHtmlChildren=function(a){for(var d=aoeu8.getOpenRoomNames(),b="",c=0;c<a.length;c++){var e=a[c];-1===$.inArray(e.name,d)&&(b+="<li class='ui-bootstrap-list-item btn' data-owner='"+e.owner+"'sn data-roomid='"+e.id+"' data-topic='"+e.topic+"'>"+e.name+"</li>")}""===b&&(b='<p class="btn" disabled>No rooms found :(</p>');return b};aoeu8.addRoomSearcher=function(a){a.bind("propertychange keyup input paste",function(){var d=a.val();aoeu8.requestRoomsFromSearchTerm(d)})};
aoeu8.requestRoomsFromSearchTerm=function(a){aoeu7.connection.send(JSON.stringify({intent:"search-rooms",searchTerm:a}))};aoeu8.handleIncomingSearchResults=function(a){a=aoeu8.createHtmlChildren(a);var d=$("#add-new-room-rooms");d.empty().append(a);d.children().each(function(a,c){$(c).click(function(){aoeu6.onNewRoomClicked(c)})})};
aoeu8.requestRoomProposals=function(){aoeu7.connection.send(JSON.stringify({intent:"room-proposals",userId:aoeu6.userId,userName:aoeu6.userName}))};aoeu8.handleIncomingRoomProposals=function(a){a=aoeu8.createHtmlChildren(a);$("#add-new-room-rooms").append(a)};aoeu7={};aoeu7.connection={};
$(function(){function a(a,b){var c=new Date;aoeu2.preferences.chat_show_traffic&&aoeu6.addVisibleMessage("",a,"_"+b+"_",c)}function d(){aoeu7.connection=new WebSocket(b);aoeu7.connection.onopen=e;aoeu7.connection.onerror=g;aoeu7.connection.onclose=k;aoeu7.connection.onmessage=h}window.WebSocket=window.WebSocket||window.MozWebSocket;window.WebSocket||console.log("Sorry, but your browser doesn't support WebSockets.");var b="ws://81.169.246.231:80",
c=aoeu7.isOnline=!0,e=function(){c=aoeu7.isOnline=!0;var a=[];$("#channels-list").children().each(function(b,c){var d=$(c);a.push({roomId:d.attr("data-roomid"),roomName:aoeu1.getSimpleText(d)})});a.forEach(function(a){aoeu7.sendUserJoin(a.roomId,a.roomName)});aoeu8.requestRoomProposals();aoeu6.enableInput();setTimeout(function(){aoeu6.isStatusPersistent=!1;aoeu6.setCurrentStatus("Welcome back!","alert-success")},1E3)},g=function(a){aoeu7.isOnline=
!1;console.log("Sorry, but there's some problem with your connection or the server is down.</p>")},k=function(){aoeu7.isOnline=!1;c&&(c=!1,aoeu6.disableInput(),aoeu9.roomAttendees={},$("#channel-attendees-entries").empty(),aoeu6.isStatusPersistent=!0,aoeu6.setCurrentStatus("Awwr. It seems we got a server problem. We're working on it...","alert-error",-1));setTimeout(function(){d();console.log("retry")},3E4)},h=function(b){b=JSON.parse(b.data);switch(b.intent){case "tell":aoeu6.addVisibleMessage(b.userName,
b.roomName,b.content,b.time);break;case "tell-image":aoeu6.addVisibleImage(b.userName,b.roomName,b.content,b.time);break;case "attendees-list":aoeu7.updateAttendeesList(b.attendees,b.roomId,b.roomName);break;case "quit-room":var c=b.userId,d=b.userName;b=b.roomName;console.log("userquit:"+c+" in "+b);if(void 0===aoeu9.roomAttendees[b])console.log("userquit with undefined roomName");else{for(var e=0;e<aoeu9.roomAttendees[b].length;++e)aoeu9.roomAttendees[b][e].userId===
c&&aoeu9.roomAttendees[b].remove(e);b===aoeu1.getSimpleText(aoeu6.activeRoom)&&$("#channel-attendees-"+c).remove();a(b,d+" quit the room.")}break;case "join-room":c=b.userId;d=b.userName;b=b.roomName;void 0===aoeu9.roomAttendees[b]&&(aoeu9.roomAttendees[b]=[]);aoeu9.roomAttendees[b].push({userId:c,userName:d});b===aoeu1.getSimpleText(aoeu6.activeRoom)&&$("#channel-attendees-entries").append(aoeu6.makeAttendeeEntry(c,d));a(b,d+
" joined the room.");break;case "room-proposals":aoeu8.handleIncomingRoomProposals(b.list);break;case "search-rooms":aoeu8.handleIncomingSearchResults(b.list,b.inputSource);break;default:console.log("Unknown `intent`.")}};d()});
aoeu7.updateAttendeesList=function(a,d,b){d=$("#channel-attendees-entries");b===aoeu1.getSimpleText(aoeu6.activeRoom)&&d.empty();void 0===aoeu9.roomAttendees[b]&&(aoeu9.roomAttendees[b]=[]);var c=b===aoeu1.getSimpleText(aoeu6.activeRoom),e="";a.forEach(function(a){aoeu9.roomAttendees[b].push({userId:a.userId,userName:a.userName});c&&(e+=aoeu6.makeAttendeeEntry(a.userId,a.userName))});d.append(e)};
aoeu7.sendUserQuit=function(a,d){aoeu7.connection.send(JSON.stringify({intent:"quit-room",userId:aoeu6.userId,userName:aoeu6.userName,roomId:a,roomName:d}))};aoeu7.sendUserJoin=function(a,d){aoeu7.connection.send(JSON.stringify({intent:"join-room",userId:aoeu6.userId,userName:aoeu6.userName,roomId:a,roomName:d}))};
aoeu7.sendMessage=function(a,d,b,c,e){aoeu7.connection.send(JSON.stringify({content:a,intent:"tell",userId:d,userName:b,roomId:c,roomName:e}))};aoeu7.sendImage=function(a,d,b,c,e){aoeu7.connection.send(JSON.stringify({content:a,intent:"tell-image",userId:d,userName:b,roomId:c,roomName:e}))};
