$(function(){function s(){$("#channels-list > li").hide();var a=$("#channels-list > li.room-favorite");a.each(function(c,b){b=$(b);var e=b.find("button > .room-close");e.click(function(){l(e)});p(b);c===a.length-1&&k(b)})}function t(){$("#channels-list > li.room-favorite").each(function(a,c){c=$(c);c.click(function(){k(c)});c.children("button").each(function(a,c){$(c).click(function(){l(c)})})});$("#view-log-button").click(function(){$(this);document.location="log/"+encodeURIComponent(b.helper.getSimpleText(b._activeRoom))});
$("#help-button").click(function(){document.location="help"});$("#submit-message").keydown(u);$("#add-new-room").click(function(){$("#add-new-room-rooms > li").each(function(a,c){$(c).click(function(){b.onNewRoomClicked(c)})})})}function v(a){var c=b.helper.getSimpleText(b._activeRoom),c=b.sstatus.logChannelAttendees[c],d=a.split(" ").pop();a=a.replace(/\w+$/,"");if(""===d)return a;var e={};try{var f=d.toLowerCase();c.forEach(function(a){if(0===a.userName.toLowerCase().indexOf(f))throw d=a.userName+
" ",e;})}catch(g){if(g!==e)throw g;}return a+d}function k(a){if(m)m=!1;else if(void 0===b._activeRoom&&(b._activeRoom=$(document.createElement("span"))),a=$(a),"add-new-room"!==a.attr("id")){b.enableInput();var c=b.helper.getSimpleText(b._activeRoom),d=b.helper.getSimpleText(a);void 0===b.sstatus.logChannelAttendees[d]&&(b.sstatus.logChannelAttendees[d]=[]);d!==c&&(q(b._activeRoom),q(a),a.addClass("btn-primary"),b._activeRoom.addClass("room-favorite"),b._activeRoom=a,b.updateChatBox(),b.updateAttendeesList(),
$("#chat-header-topic").html(a.attr("data-topic")),a.attr("data-owner")===$("#user-id").html()?0===$("#room-settings").length&&$("#chat-header-topic").after('<button class="btn" id="room-settings" href="#modal-room-pref" data-toggle="modal"><img src="img/icon/room_settings.png" />Room settings</button>'):$("#room-settings").remove(),a=a.children(".unseen-messages"),a.hide("slow"),a.text("0"))}}function q(a){a.removeClass("btn-warning btn-danger btn-primary btn-info btn-success")}function l(a){m=!0;
var c=$(a).parent();a=c.attr("data-roomid");var d=b.helper.getSimpleText(c),e=c.attr("data-topic"),f=c.attr("data-owner");b.helper.submitHttpRequest("remove-favorite.php",{userId:$("#user-id").html(),roomId:a});b.support.isChrome||b.support.isFirefox||b.support.isOpera?(c.css("maxHeight",c.height()),c.animate({width:"0","padding-left":"0","padding-right":"0"},200,"swing",function(){c.remove()})):c.remove();var g=b.helper.getSimpleText(c)===b.helper.getSimpleText(b._activeRoom);(1>=c.parent().children().length||
g)&&b.disableInput();w(a,d,e,f);b.chat.sendUserQuit(a,d);delete b.sstatus.logChannelAttendees[d]}function p(a){var c=a.css("padding-left"),b=a.width();a.css("maxHeight",a.height());a.width(0);a.css("padding-left",0);a.css("padding-right",0);a.show();a.animate({width:b,"padding-left":c,"padding-right":c},200,function(){a.removeAttr("style")})}function w(a,c,d,e){var f=$("#add-new-room-popover > div:nth-child(2) ul"),g=$(document.createElement("li")).addClass("ui-bootstrap-list-item btn room-favorite").attr("data-roomid",
a).attr("data-topic",d).attr("data-owner",e).text(c);g.click(function(){b.onNewRoomClicked(g[0])});f.prepend(g)}function r(a,c,d){var e="";"server"===a&&(e="server-message");a===b._userName&&(a="<b>"+a+"&nbsp;</b>");a='<div class="chat-entry '+e+'"><span class="chat-entry-options">'+b.helper.toHHMMSS(d)+'</span><span class="chat-entry-user ">&nbsp;'+a+'</span><span class="chat-entry-message">'+c+"</div>";return $(a)}var b=this;this._userName=$("#user-name > button").text().trim();this.modals=new __modals__(this);
this.sstatus=new __status__;this.chat=new __chat__(this,this.sstatus);this.helper=new __helper__;this.sound=new __sound__(this.modals);this.formatMessages=new __format_messages__(this.modals);this.support={};var n=navigator.userAgent.toLowerCase();this.support.isChrome=-1<n.indexOf("chrome");this.support.isOpera=-1<n.indexOf("opera");this.support.isFirefox=-1<n.indexOf("firefox");$(document).ready(function(){s();t();$(window).resize();new __tip_poster__(b);new __image_upload__(b)});this.isStatusPersistent=
!1;this.setCurrentStatus=function(a,c,d){d=void 0===d?5E3:d;var e=$("#site-status");"-50px"!==e.css("margin-top")?e.animate({"margin-top":"-50px"},1E3,function(d,e,h){b.setCurrentStatus(a,c,h)}):(e.removeClass("alert-warning alert-error alert-info alert-success"),e.addClass(c),e.html(a),e.animate({"margin-top":"20px"},1E3),setTimeout(function(){b.isStatusPersistent||e.animate({"margin-top":"-50px"},1E3)},d))};this.makeAttendeeEntry=function(a,c){return'<li id="channel-attendees-'+a+'"><button disabled class="btn">'+
c+"</button></li>"};var u=function(a){var c=$("#submit-message"),d=[],e=-1,f;return function(a){switch(a.which){case 13:x()&&(a=b.helper.htmlEncode(c.val()).trim(),0<a.length&&(500<a.length&&(a=a.substr(0,500)),b.chat.sendMessage(a,$("#user-id").text(),b._userName,b._activeRoom.attr("data-roomid"),b.helper.getSimpleText(b._activeRoom)),c.val(""),d.unshift(a),e=-1));break;case 9:var h=c.val();""!==h&&(a.preventDefault(),c.val(v(h)));break;case 38:-1===e&&(f=c.val());e<d.length-1&&(e++,c.val(d[e]));
break;case 40:e--,-1>=e?(c.val(f),e=-1):c.val(d[e])}}}(),y=function(){var a=RegExp(".*[\\s:;.,|<>]?"+b._userName+"[\\s:;.,!|<>]?.*","g");return function(c){return a.test(c)}}();this.logChatMessage=function(a,c,d,e){void 0===b.sstatus.logMessages[a]&&(b.sstatus.logMessages[a]=[]);void 0===b.sstatus.logUsers[a]&&(b.sstatus.logUsers[a]=[]);void 0===b.sstatus.logTimes[a]&&(b.sstatus.logTimes[a]=[]);b.sstatus.logMessages[a].push(d);b.sstatus.logUsers[a].push(c);b.sstatus.logTimes[a].push(e)};this.addVisibleMessage=
function(a,c,d,e,f){b.logChatMessage(c,a,d,e);c!==b.helper.getSimpleText(b._activeRoom)?(c=$("#channels-list").find('li:contains("'+c+'")'),""!==a&&(y(d)?(b.sound.playUserAddressed(),$.titleAlert("Someone talked to you!"),c.removeClass("room-favorite"),c.addClass("btn-danger")):(a=c.children(".unseen-messages"),d=parseInt(a.text(),10),0===d&&a.show("slow"),a.text(d+1)))):(a=!0===f?b.makeEntryImage(a,d,e):b.makeEntryMessage(a,d,e),d=$("#chat-entries"),d.append(a),d.animate({scrollTop:d.scrollTop()+
500},100),a=a.children(),d=$(a[2]).height(),$(a[0]).height(d),$(a[1]).height(d),b.modals.liveUpdateChatTextSize())};this.makeImageTagFromUrl=function(a){return'<span class="image-tooltip"><img src="'+a+'"></img><span><img src="'+a+'"></img></span></span>'};this.addVisibleImage=function(a,c,d,e){d=b.makeImageTagFromUrl(d);b.addVisibleMessage(a,c,d,e,!0)};this.updateChatBox=function(){var a=$("#chat-entries");a.empty();var c=b.helper.getSimpleText(b._activeRoom);if(void 0!==b.sstatus.logMessages[c]){for(var d=
b.sstatus.logMessages[c].length,e=0;e<d;++e){var f=b.sstatus.logUsers[c][e];f==b._userName&&(f="<b>"+f+"</b>");a.append(b.makeEntryMessage(f,b.sstatus.logMessages[c][e],b.sstatus.logTimes[c][e]))}b.modals.liveUpdateChatTextSize();$(window).resize();a.scrollTop(a.height())}};this.updateAttendeesList=function(){var a=b.helper.getSimpleText(b._activeRoom);if(void 0!==b.sstatus.logChannelAttendees[a]){var c=$("#channel-attendees-entries");c.empty();for(var a=b.sstatus.logChannelAttendees[a],d=0;d<a.length;++d){var e=
a[d];c.append(b.makeAttendeeEntry(e.userId,e.userName))}}};var m=!1;this.onNewRoomClicked=function(a){b.enableInput();var c=$(a),d=c.text();a=c.attr("data-roomid");var e=c.attr("data-topic"),f=c.attr("data-owner");b.helper.submitHttpRequest("add-favorite.php",{userId:$("#user-id").html(),roomId:a});b.chat.sendUserJoin(a,d);b._activeRoom.removeClass("btn-primary");$("#chat-header-topic").html(b.formatMessages.makeLinksClickable(e));$("#chat-entries").empty();a=b.openRoom(a,d,e,f);var e=$("#add-new-room").next(),
f=parseInt(e.css("left"),10),g=a.width(),h=a.css("padding-left"),g=g+2*parseInt(h,10)+6;e.animate({left:f+g},200);(b.support.isChrome||b.support.isFirefox||b.support.isOpera)&&p(a);c.animate({height:0,"padding-top":0,"padding-bottom":0},200,function(){c.remove();$('#add-new-room-popover > div:nth-child(2) ul > li:contains("'+d+'")').remove()});b._activeRoom=a};this.openRoom=function(a,c,b,e){var f=$('<li class="btn btn-primary room-favorite"/>');f.attr("data-roomid",a);f.attr("data-topic",b);f.attr("data-owner",
e);f.text(c);k(f);f.click(function(){k(f)});var g=$('<button class="close room-close" style="margin-top:-2px;">&times;</button>');a=$('<span class="unseen-messages"></span>');g.click(function(){l(g[0])});f.append(g);f.append(a);$("#channels-list").append(f);return f};this.enableInput=function(){var a=$("#submit-message");$("#chat-entries").removeAttr("disabled");a.removeAttr("disabled");a.focus();$("#view-log-button").show();$("#room-settings").show()};this.disableInput=function(){var a=$("#submit-message");
$("#chat-entries").attr("disabled","disabled");a.attr("disabled","disabled");a.blur();$("#chat-header-topic").text("");$("#view-log-button").hide();$("#room-settings").hide()};var x=function(){var a=[];return function(){a.push((new Date).getTime());if(3<a.length&&(a.shift(),!(3E3<a[2]-a[0]))){var b=$("#submit-status");b.is(":visible")||(b.removeClass(),b.empty(),b.addClass("alert alert-error"),b.append("<h4>Man, calm down!</h4>"),b.append("Your mission is not to spam the room. :P").hide().show("slow"),
setTimeout(function(){b.hide("quick")},5E3));return!1}return!0}}();this.makeEntryMessage=function(a,c,d){c=b.formatMessages.styleMessage(c);return r(a,c,d)};this.makeEntryImage=function(a,b,d){return r(a,b,d)}});
