function __modals__(c){function f(a,b){c.helper.submitHttpRequest("update-profile.php",a,b)}function k(a,b){c.helper.submitHttpRequest("update-new-room.php",a,b)}function l(a,b){c.helper.submitHttpRequest("update-room-pref.php",a,b)}function g(){var a=b.room_pref.isTopicLengthOk;$("#modals-room-pref-delete").is(":checked")&&(a=!0);b.room_pref.isPasswordLengthOk&&a?$("#modal-room-pref-submit").removeAttr("disabled"):$("#modal-room-pref-submit").prop("disabled",!0)}var b=this;this.preferences={};this.preferences.enable_smilies=
$("#modals-pref-enable-smilies").prop("checked");this.preferences.enable_formatting=$("#modals-pref-enable-formatting").prop("checked");this.preferences.enable_notification_sounds=$("#modals-pref-enable-notification-sounds").prop("checked");this.preferences.chat_show_traffic=$("#modals-pref-chat-show-traffic").prop("checked");this.preferences.chat_text_size=$("#modals-pref-textsize").val();this.preferences.chat_text_font=$("#modals-pref-font").val();this.preferences.enable_tips=$("#modals-pref-enable-tips").val();
this.preferences.user_id=$("#user-id").html();this.updateChatBoxCallback=c.updateCheckBox;$(document).ready(function(){b.liveUpdateChatTextSize();b.liveUpdateFont();$("#modals-profile-current-password-info, #modals-room-pref-current-password-info").popover({trigger:"hover",placement:"left",title:"Why do I need to confirm my password?",content:"Security. It is all about confidential information which we try to keep as secure as possible."})});$("#modal-pref-submit").click(function(a){$("#modal-pref").modal("hide");
c.helper.submitHttpRequest("update-preferences.php",b.preferences)});$("#modals-pref-enable-smilies").change(function(){b.preferences.enable_smilies=$(this).is(":checked");b.updateChatBoxCallback()});$("#modals-pref-enable-formatting").change(function(){b.preferences.enable_formatting=$(this).is(":checked");b.updateChatBoxCallback()});$("#modals-pref-enable-notification-sounds").change(function(){b.preferences.enable_notification_sounds=$(this).is(":checked")});$("#modals-pref-textsize").change(function(){b.preferences.chat_text_size=
$(this).val();b.liveUpdateChatTextSize()});$("#modals-pref-font").change(function(){b.preferences.chat_text_font=$(this).val();b.liveUpdateFont()});$("#modals-pref-chat-show-traffic").change(function(){b.preferences.chat_show_traffic=$(this).is(":checked")});$("#modals-pref-enable-tips").change(function(){b.preferences.enable_tips=$(this).is(":checked")});this.liveUpdateFont=function(){var a=$("#modals-pref-font option:selected").val();$("body *").css("font-family",a)};this.liveUpdateChatTextSize=
function(){var a=$("#modals-pref-textsize option:selected").text().replace(" ","");$("#chat-entries").css("font-size",a);var a=parseInt(a,10),b;b=16<=a?210:150;$(".chat-entry-user").css("width",b);a-=10;$("#chat .chat-entry > *").css("padding-top",a+"px").css("padding-bottom",a+"px");$(window).resize()};$("#modal-profile").on("shown",function(){$("#modals-profile-current-password").focus()});$("#modals-profile-current-password").bind("propertychange keyup input paste",function(){var a=$(this).val().length;
8<=a&&20>=a?$("#modal-profile-submit").removeAttr("disabled"):$("#modal-profile-submit").prop("disabled",!0)});$("#modal-profile-submit").click(function(a){a=$("#modals-profile-delete");if(a.is(":checked"))confirm("If you confirm now, your account will be permanently removed and you will not be able to log in with this user again. Do you still want to confirm the account deletion?")?($("#modal-profile").modal("hide"),a={intent:"delete-account"},a.userId=$("#user-id").html(),a.currentPassword=$("#modals-profile-current-password"),
f(a),document.location.href="why-account-deletion.php"):a.prop("checked",!1);else{$("#modal-profile").modal("hide");var b=$("#modals-profile-current-password"),h=$("#modals-profile-new-password");a={intent:"change-password"};a.userId=$("#user-id").html();a.currentPassword=b.val();a.newPassword=h.val();b.val("");h.val("");f(a,function(a){var b=a.split(">");a=b[0];b=parseInt(b[1],10);switch(a){case "delete-account":break;case "change-password":1===parseInt(b,10)?c.setCurrentStatus("Password changed successfully.",
"alert-success"):c.setCurrentStatus("Sorry man, I couldn't verify that password.","alert-warning");break;default:console.log("unknown intent returned")}})}});$("#modal-new-room").on("show",function(){$("#add-new-room").popover("hide")});$("#modal-new-room").on("shown",function(){$("#modals-new-room-name").focus()});this.new_room={};this.new_room.isNameAvailable=!1;this.new_room.isNameLengthOk=!1;this.new_room.isTopicLengthOk=!1;this.verifyNewRoomInput=function(){b.new_room.isNameLengthOk&&b.new_room.isTopicLengthOk&&
b.new_room.isNameAvailable?$("#modal-new-room-submit").removeAttr("disabled"):$("#modal-new-room-submit").prop("disabled",!0)};$("#modals-new-room-name").bind("propertychange keyup input paste",function(){var a=$(this).val().trim(),d=a.length;b.new_room.isNameLengthOk=3<=d&&20>=d;b.new_room.isNameLengthOk&&(d={},d.roomname=a,c.helper.submitHttpRequest("does-roomname-exist.php",d,function(a){1===parseInt(a,10)?(b.new_room.isNameAvailable=!1,$("#modals-new-room-name-status").show()):(b.new_room.isNameAvailable=
!0,$("#modals-new-room-name-status").hide());b.verifyNewRoomInput()}));b.verifyNewRoomInput()});$("#modals-new-room-topic").bind("propertychange keyup input paste",function(){var a=$(this).val().trim().length;b.new_room.isTopicLengthOk=20<=a&&200>=a;b.verifyNewRoomInput()});$("#modal-new-room-submit").click(function(a){$("#modal-new-room").modal("hide");var b={};b.name=$("#modals-new-room-name").val().trim();b.owner=$("#user-id").text();b.topic=$("#modals-new-room-topic").val().trim();k(b,function(a){$("#modals-new-room-name").val("");
$("#modals-new-room-topic").val("");c.openRoom(a,b.name,b.topic);c.chat.sendUserJoin(a,b.name);c.chat.sendMessage("You just created the room <b>"+b.name+"</b>, congratulations!",-1,"server",a,b.name);var e={};e.userId=b.owner;e.roomId=a;c.helper.submitHttpRequest("add-favorite.php",e)})});this.room_pref={};this.room_pref.isRoomNameToTitleAdded=!1;this.room_pref.isPasswordLengthOk=!1;this.room_pref.isTopicLengthOk=!1;this.room_pref.currentTopic="";$("#modal-room-pref").on("show",function(){if(!b.room_pref.isRoomNameToTitleAdded){b.room_pref.isRoomNameToTitleAdded=
!0;var a=$("#modal-room-pref h3:first");a.html("<u>"+c.helper.getSimpleText(c._activeRoom)+"</u>"+a.html())}b.room_pref.currentTopic=c._activeRoom.data("topic");$("#modals-room-pref-topic").val(b.room_pref.currentTopic).keyup()});$("#modal-room-pref").on("shown",function(){$("#modals-room-pref-topic").focus().val("").val(c._activeRoom.data("topic"))});$("#modal-room-pref-submit").click(function(){$("#modal-room-pref").modal("hide");var a={};a.roomTopic=$("#modals-room-pref-topic").val().trim();a.roomId=
c._activeRoom.data("roomid");a.userId=$("#user-id").html();a.userPassword=$("#modals-room-pref-current-password").val();a.roomTopic!==b.room_pref.currentTopic&&l(a,function(b){$("#modals-room-pref-current-password").val("");1<=parseInt(b,10)?(c._activeRoom.data("topic",a.roomTopic),$("#chat-header-topic").html(c.formatMessages.makeLinksClickable(a.roomTopic))):c.setCurrentStatus("Sorry man, I couldn't verify that password.","alert-warning")})});$("#modals-room-pref-current-password").bind("propertychange keyup input paste",
function(){var a=$(this).val().trim().length;b.room_pref.isPasswordLengthOk=8<=a&&30>=a;g()});$("#modals-room-pref-topic").bind("propertychange keyup input paste",function(){var a=$(this).val().trim().length;b.room_pref.isTopicLengthOk=20<=a&&200>=a;g()})};
